In [3]:
# 필요한 라이브러리를 불러옵니다.
import numpy as np

### 1. 값이 10~49인 numpy array를 만드세요

In [18]:
z = np.arange(10, 49)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


### 2. z를 반전하세요.

In [19]:
z = z[::-1]
print(z)

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


### 3. 반전시킨 z 매트릭스를 10 x 4 매트릭스로 바꾸세요.

In [23]:
z = np.resize(z, (10, 4)) # resize를 사용하면 빈 자리를 데이터를 반복하여 채운다(48부터 다시 반복)
print(z)

[[48 47 46 45]
 [44 43 42 41]
 [40 39 38 37]
 [36 35 34 33]
 [32 31 30 29]
 [28 27 26 25]
 [24 23 22 21]
 [20 19 18 17]
 [16 15 14 13]
 [12 11 10 48]]


### 4. x에서 0이 아닌 요소의 색인을 찾아보세요.

In [30]:
x = np.array([5,6,8,0,1,0,7])
nz_idx = np.nonzero(x)
print(nz_idx)

(array([0, 1, 2, 4, 6]),)


### nan 값 이해하기



In [31]:
print(np.nan == np.nan)
print(np.isnan(np.nan))

import math
print(0.3 == 3 * 0.1)
print(math.isclose(0.1 + 0.2, 0.3))

False
True
False
True


### 5. 12 x 12 매트릭스를 만들어 바둑판 패턴으로 0과 1을 채우세요

In [165]:
x = np.zeros((12, 12))
print(x, end='\n\n')
###############
# 슬라이싱을 사용하세요
for i in range(len(x)):
    if i%2 == 0:
        x[i][1::2] = 1
    else:
        x[i][0::2] = 1
###############
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

[[0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]]


### 6. np.tile 을 이용해서 동일한 바둑판 배턴을 만들어보세요

In [8]:
x = np.tile([[0, 1],[1, 0]], (6, 6))
print(x)

[[0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]]


### 7. 1차원 배열이 x에서 값이 5~10인 요소를 0으로 바꾸세요

In [191]:
x = np.array([2,5,3,8,3,34,23,7,10])

new = [i for i in x if i>=5] # 5이상인 값만 따로 빼기
new

[5, 8, 34, 23, 7, 10]

In [189]:
x = np.array([2,5,3,8,3,34,23,7,10])

new = [i if i>=5 else 0 for i in x] # 5이상이면 그대로 가져오고 아니면 0으로 변환해서 가져옴
new

[0, 5, 0, 8, 0, 34, 23, 7, 10]

In [192]:
x = np.array([2,5,3,8,3,34,23,7,10])
print(x)
##################
# 필터링을 사용하세요.
def con(n):
    i if i>=5 else 0 for i in x
    
x = filter(con, x)

##################
print(x)

SyntaxError: invalid syntax (4273011870.py, line 6)

### 8. 0에서 100 사이의 값으로 크기가 10인 1차원 array를 만드세요

In [19]:
x = np.random.randint(0, 100, 10)
print(x)

[27 35 91 69 49 39 78 73 99 48]


### 9. np.allclose() 함수를 사용하여 2개의 array가 같은지를 확인해보세요

In [20]:
A = np.array([1e10,1e-8])
B = np.array([1.00001e10,1e-9])

equal = np.allclose(A, B)
print(equal)

True


### 10. 데카르트 좌표를 나타내는 랜덤 8 x 2 행렬을 고려하여 극좌표로 변환해보세요.

In [102]:
coord = np.random.random((10,2))
x, y = coord[:,0], coord[:,1]
r = x**2 + y**2
theta = x / r
ploar_coord = np.concatenate([r[:,np.newaxis], theta[:,np.newaxis]],axis=1)
print(ploar_coord)

[[0.25448066 1.15190582]
 [0.91513225 1.04227648]
 [0.71248906 0.80933779]
 [0.6943551  0.27811324]
 [0.44531314 0.94837777]
 [0.10710258 1.81818494]
 [0.64849544 1.05610814]
 [1.26954224 0.56305915]
 [0.49874787 0.47241885]
 [0.27159557 0.60990955]]
